---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: deployment-roman-obsplan-snana-summ-snana-strategy
  name: snana-strategy
  namespace: roman-obsplan-snana-summ
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-roman-obsplan-snana-summ-snana-strategy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-roman-obsplan-snana-summ-snana-strategy
    spec:
      containers:
      - image: registry.nersc.gov/m4385/raknop/snana-summary-webserver
        imagePullPolicy: Always
        name: decat-upload
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 95089
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /data
          name: snana-summ-data
          readOnly: true
        - mountPath: /snana_sim
          name: snana-summ-snana-sim
          readOnly: true
        # Comment this out to use the code baked into the Dockerfile
        - mountPath: /code
          name: snana-summ-code
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 101320
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: registry-nersc
      volumes:
      - hostPath:
          path: /global/cfs/cdirs/m4385/survey_strategy_optimization/snana_summary_webserver_data/current
          type: Directory
        name: snana-summ-data
      - hostPath:
          path: /global/cfs/cdirs/m4385/survey_strategy_optimization/snana_summary_webserver_data/snana_sim/2024-04-16_x420
          type: Directory
        name: snana-summ-snana-sim
      - hostPath:
          path: /global/cfs/cdirs/m4385/survey_strategy_optimization/code/snana-summary-dev-webserver
          type: Directory
        name: snana-summ-code
---
apiVersion: v1
kind: Service
metadata:
  name: snana-strategy
  namespace: roman-obsplan-snana-summ
spec:
  clusterIP: None
  clusterIPs:
  - None
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  selector:
    workload.user.cattle.io/workloadselector: deployment-roman-obsplan-snana-summ-snana-strategy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: snana-summ-ingress
  namespace: roman-obsplan-snana-summ
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: deployment-roman-obsplan-snana-summ-snana-strategy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snana-strategy
  namespace: roman-obsplan-snana-summ
spec:
  rules:
  - host: snana-strategy.roman-obsplan-snana-summ.development.svc.spin.nersc.org
    http:
      paths:
      - backend:
          service:
            name: snana-summ-ingress
            port:
              number: 8080
        pathType: ImplementationSpecific
  - host: roman-snpit-snana-strategy-dev.lbl.gov
    http:
      paths:
      - backend:
          service:
            name: snana-summ-ingress
            port:
              number: 8080
        pathType: ImplementationSpecific
  tls:
  # - hosts:
  #   - snana-summ.roman-obsplan-snana-summ.development.svc.spin.nersc.org
  - hosts:
    - roman-snpit-snana-strategy-dev.lbl.gov
    secretName: snana-strategy-cert
---
